### PR TITLE
Moving best practices from Public Candidates to this repo

### PR DESCRIPTION
**Pull request by prajectory**
Fixes # .

## Changes proposed in this pull request:
- Move them to the standard repo
- Get people to contribute ( Include all and even the ones that are niche) 
- Link them to the standard
-
-

## Propagation of Changes

Identify where of the following the proposed changes need to be propagated, and include the relevant pull request where appropriate:

- [ ] The DPGA website contains https://digitalpublicgoods.net/standard/ which needs to be updated manually matching the contents of [standard.md](https://github.com/DPGAlliance/DPG-Standard/blob/master/standard.md).
- [ ] The DPGA website also contains the [submission guide](https://digitalpublicgoods.net/submission-guide/) which needs to be updated manually.
- [ ] The [unicef/publicgoods-candidates](https://github.com/unicef/publicgoods-candidates) repository needs the following to be updated:
    - [ ] the [nominee-schema.json](https://github.com/unicef/publicgoods-candidates/blob/master/nominee-schema.json)
    - [ ] the [screening-schema.json](https://github.com/unicef/publicgoods-candidates/blob/master/screening-schema.json)
    - [ ] propagate any changes to all encoded nominees and digital public goods.
    - Link to the corresponding pull request: unicef/publicgoods-candidates#
- [ ] The [Submission Form](https://digitalpublicgoods.net/submission) through the [unicef/publicgoods-submission](https://github.com/unicef/publicgoods-submission) repository, and its corresponding [schema.js](https://github.com/lacabra/submission-digitalpublicgoods/blob/master/schemas/schema.js)
    - Link to the corresponding pull request:
- [ ] The [Eligibility Form](https://digitalpublicgoods.net/eligibility/) through the [unicef/publicgoods-scripts](https://github.com/unicef/publicgoods-submission) repository, by editing [quizQuestions.js](https://github.com/unicef/publicgoods-scripts/blob/master/packages/eligibility/src/api/quizQuestions.js)
    - Link to the corresponding pull request:

### CODE REVIEW

**Review by downeymj — CHANGES_REQUESTED** [review]
FYI, this file does not currently seem to have an extension, e.g., `.md`.

**Comment by nathanbaleeta** [comment]
@prajectory the following documentation currently make up the preliminary work on the help center:
[Approved Licenses for Digital Public Goods](https://github.com/DPGAlliance/publicgoods-candidates/blob/main/docs/licenses.md)
[Documentation Resources](https://github.com/DPGAlliance/publicgoods-candidates/blob/main/docs/help-center/documentation.md)
[Best Practices Resouces](https://github.com/DPGAlliance/publicgoods-candidates/blob/main/docs/help-center/best-practices.md)
[Open Standards Resources](https://github.com/DPGAlliance/publicgoods-candidates/blob/main/docs/help-center/open-standards.md)
[Data Privacy Resources](https://github.com/DPGAlliance/publicgoods-candidates/blob/main/docs/help-center/privacy.md)

**Comment by prajectory** [comment]
@nathanbaleeta Noted. Thanks for that list.

**Review by nathanbaleeta — COMMENTED** [review]
@prajectory the following documentation currently make up the preliminary work for the help center:

- [Approved Licenses for Digital Public Goods](https://github.com/DPGAlliance/publicgoods-candidates/blob/main/docs/licenses.md)
- [Documentation Resources](https://github.com/DPGAlliance/publicgoods-candidates/blob/main/docs/help-center/documentation.md)
- [Best Practices Resouces](https://github.com/DPGAlliance/publicgoods-candidates/blob/main/docs/help-center/best-practices.md)
- [Open Standards Resources](https://github.com/DPGAlliance/publicgoods-candidates/blob/main/docs/help-center/open-standards.md)
- [Data Privacy Resources](https://github.com/DPGAlliance/publicgoods-candidates/blob/main/docs/help-center/privacy.md)

So are you proposing the entire help center migrate to the DPG Standards repo?

**Pull request closed without merging**
